name: clinical_advisor
description: Reusable clinical advisor engine (role/region aware) with JSON knowledge base.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0

dev_dependencies:
  test: ^1.25.0
  lints: ^3.0.0







