import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  Locale _currentLocale = const Locale('tr', 'TR');
  bool _isInitialized = false;

  final Map<String, Map<String, String>> _translations = {
    'tr': {
      // Genel
      'app_title': 'PsyClinic AI',
      'welcome': 'Hoş Geldiniz',
      'login': 'Giriş Yap',
      'logout': 'Çıkış Yap',
      'save': 'Kaydet',
      'cancel': 'İptal',
      'delete': 'Sil',
      'edit': 'Düzenle',
      'add': 'Ekle',
      'search': 'Ara',
      'filter': 'Filtrele',
      'close': 'Kapat',
      'ok': 'Tamam',
      'yes': 'Evet',
      'no': 'Hayır',
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'success': 'Başarılı',
      'warning': 'Uyarı',
      'info': 'Bilgi',
      
      // Dashboard
      'dashboard': 'Dashboard',
      'home': 'Ana Sayfa',
      'patients': 'Hastalar',
      'appointments': 'Randevular',
      'ai_diagnosis': 'AI Tanı',
      'telemedicine': 'Telemedicine',
      'security': 'Güvenlik',
      'analytics': 'Analitik',
      'roles': 'Roller',
      'patient_portal': 'Hasta Portalı',
      'voice_notes': 'Sesli Notlar',
      'billing': 'Faturalandırma',
      'insurance': 'Sigorta',
      'e_prescription': 'E-Reçete',
      'advanced_search': 'Arama',
      'mood_tracking': 'Mood',
      'ai_assistant': 'AI Asistan',
      
      // Hasta Yönetimi
      'patient_management': 'Hasta Yönetimi',
      'patient_name': 'Hasta Adı',
      'patient_id': 'Hasta ID',
      'diagnosis': 'Tanı',
      'last_session': 'Son Seans',
      'status': 'Durum',
      'active': 'Aktif',
      'inactive': 'Pasif',
      'new_patient': 'Yeni Hasta',
      'patient_details': 'Hasta Detayları',
      'patient_history': 'Hasta Geçmişi',
      'add_patient': 'Hasta Ekle',
      'edit_patient': 'Hasta Düzenle',
      'delete_patient': 'Hasta Sil',
      
      // Randevu Sistemi
      'appointment_system': 'Randevu Sistemi',
      'appointment_date': 'Randevu Tarihi',
      'appointment_time': 'Randevu Saati',
      'doctor': 'Doktor',
      'appointment_type': 'Randevu Türü',
      'appointment_status': 'Randevu Durumu',
      'scheduled': 'Planlandı',
      'completed': 'Tamamlandı',
      'cancelled': 'İptal Edildi',
      'rescheduled': 'Ertelendi',
      'new_appointment': 'Yeni Randevu',
      'reschedule_appointment': 'Randevu Ertle',
      'cancel_appointment': 'Randevu İptal Et',
      
      // AI Tanı
      'ai_diagnosis': 'AI Destekli Tanı',
      'symptoms': 'Semptomlar',
      'patient_history_input': 'Hasta Geçmişi',
      'get_diagnosis': 'Tanı Al',
      'ai_result': 'AI Tanı Sonucu',
      'risk_assessment': 'Risk Değerlendirmesi',
      'recommended_treatment': 'Önerilen Tedavi',
      'possible_diagnosis': 'Olası Tanı',
      
      // Telemedicine
      'video_call': 'Video Görüşme',
      'start_call': 'Görüşmeyi Başlat',
      'end_call': 'Görüşmeyi Sonlandır',
      'mute_mic': 'Mikrofonu Kapat',
      'unmute_mic': 'Mikrofonu Aç',
      'turn_off_camera': 'Kamerayı Kapat',
      'turn_on_camera': 'Kamerayı Aç',
      'screen_share': 'Ekran Paylaşımı',
      'local_video': 'Yerel Video Akışı',
      'remote_video': 'Uzak Video Akışı',
      
      // Güvenlik
      'security_settings': 'Güvenlik Ayarları',
      'biometric_auth': 'Biyometrik Kimlik Doğrulama',
      'two_factor_auth': 'İki Faktörlü Kimlik Doğrulama',
      'audit_logs': 'Denetim Kayıtları',
      'encryption_settings': 'Şifreleme Ayarları',
      'password_change': 'Şifre Değiştir',
      'security_report': 'Güvenlik Raporu',
      
      // Analitik
      'analytics_reporting': 'Analitik ve Raporlama',
      'total_patients': 'Toplam Hasta',
      'monthly_revenue': 'Aylık Gelir',
      'average_sessions': 'Ortalama Seans Sayısı',
      'new_patients_this_month': 'Yeni Hasta (Bu Ay)',
      'monthly_sessions': 'Aylık Seans Sayısı',
      'performance_metrics': 'Performans Metrikleri',
      'trend_analysis': 'Trend Analizi',
      
      // Hasta Portalı
      'patient_portal': 'Hasta Portalı',
      'book_appointment': 'Randevu Al',
      'send_message': 'Mesaj Gönder',
      'make_payment': 'Ödeme Yap',
      'upload_file': 'Dosya Yükle',
      'upcoming_appointments': 'Yaklaşan Randevular',
      'recent_messages': 'Son Mesajlar',
      'treatment_plan': 'Tedavi Planı',
      'lab_results': 'Laboratuvar Sonuçları',
      'download': 'İndir',
      'share': 'Paylaş',
      
      // Sesli Notlar
      'voice_notes': 'Sesli Notlar',
      'start_recording': 'Kayıt Başlat',
      'pause_recording': 'Kayıt Duraklat',
      'stop_recording': 'Kayıt Durdur',
      'play_note': 'Notu Oynat',
      'pause_note': 'Notu Duraklat',
      'recording_duration': 'Kayıt Süresi',
      'transcription': 'Transkripsiyon',
      'note_title': 'Not Başlığı',
      'save_note': 'Notu Kaydet',
      'delete_note': 'Notu Sil',
      'no_voice_notes': 'Henüz ses notu yok',
      
      // Faturalandırma
      'billing_system': 'Faturalandırma Sistemi',
      'invoices': 'Faturalar',
      'payments': 'Ödemeler',
      'insurance_claims': 'Sigorta Talepleri',
      'total_invoice': 'Toplam Fatura',
      'pending': 'Bekleyen',
      'overdue': 'Gecikmiş',
      'paid': 'Ödendi',
      'invoice_id': 'Fatura ID',
      'due_date': 'Vade Tarihi',
      'total_amount': 'Toplam Tutar',
      'payment_method': 'Ödeme Yöntemi',
      'bank_transfer': 'Banka Havalesi',
      'credit_card': 'Kredi Kartı',
      'cash': 'Nakit',
      'create_invoice': 'Fatura Oluştur',
      'send_invoice': 'Fatura Gönder',
      'view_invoice': 'Faturayı Görüntüle',
      
      // Sigorta
      'insurance_integration': 'Sigorta Entegrasyonu',
      'insurance_companies': 'Sigorta Şirketleri',
      'patient_insurance': 'Hasta Sigortaları',
      'claims': 'Talepler',
      'active_companies': 'Aktif Şirketler',
      'average_coverage': 'Ortalama Kapsama',
      'policy_number': 'Poliçe Numarası',
      'coverage_type': 'Kapsama Türü',
      'coverage_amount': 'Kapsama Tutarı',
      'remaining_amount': 'Kalan Tutar',
      'valid_from': 'Geçerlilik Başlangıcı',
      'valid_to': 'Geçerlilik Bitişi',
      'expired': 'Süresi Dolmuş',
      'exhausted': 'Tükendi',
      'sync_company': 'Senkronize Et',
      'view_company_details': 'Şirket Detayları',
      'check_coverage': 'Kapsama Kontrol',
      'view_insurance_details': 'Sigorta Detayları',
      'claim_amount': 'Talep Tutarı',
      'approved_amount': 'Onaylanan Tutar',
      'claim_status': 'Talep Durumu',
      'approved': 'Onaylandı',
      'under_review': 'İnceleniyor',
      'rejected': 'Reddedildi',
      'track_claim': 'Talep Takip Et',
      
      // E-Reçete
      'e_prescription_system': 'E-Reçete Sistemi',
      'medications': 'İlaçlar',
      'prescriptions': 'Reçeteler',
      'pharmacies': 'Eczaneler',
      'medication_name': 'İlaç Adı',
      'generic_name': 'Etken Madde',
      'dosage': 'Dozaj',
      'form': 'Form',
      'category': 'Kategori',
      'stock': 'Stok',
      'price': 'Fiyat',
      'prescription_required': 'Reçete Gerekli',
      'side_effects': 'Yan Etkiler',
      'interactions': 'Etkileşimler',
      'add_to_prescription': 'Reçeteye Ekle',
      'prescription_id': 'Reçete ID',
      'frequency': 'Sıklık',
      'duration': 'Süre',
      'instructions': 'Talimatlar',
      'insurance_coverage': 'Sigorta Kapsaması',
      'patient_payment': 'Hasta Ödemesi',
      'send_to_pharmacy': 'Eczaneye Gönder',
      'pharmacy_name': 'Eczane Adı',
      'pharmacy_address': 'Eczane Adresi',
      'pharmacy_phone': 'Eczane Telefonu',
      'distance': 'Mesafe',
      'rating': 'Puan',
      'delivery_available': 'Teslimat Mevcut',
      'call_pharmacy': 'Eczaneyi Ara',
      'send_prescription': 'Reçete Gönder',
      
      // Gelişmiş Arama
      'advanced_search': 'Gelişmiş Arama',
      'search_query': 'Arama Sorgusu',
      'search_category': 'Arama Kategorisi',
      'date_range': 'Tarih Aralığı',
      'all_categories': 'Tüm Kategoriler',
      'last_7_days': 'Son 7 Gün',
      'last_30_days': 'Son 30 Gün',
      'last_3_months': 'Son 3 Ay',
      'last_6_months': 'Son 6 Ay',
      'last_year': 'Son 1 Yıl',
      'all_time': 'Tüm Zamanlar',
      'saved_searches': 'Kayıtlı Aramalar',
      'trends': 'Trendler',
      'search_results': 'Arama Sonuçları',
      'no_results': 'Sonuç bulunamadı',
      'search_history': 'Arama Geçmişi',
      'advanced_filters': 'Gelişmiş Filtreler',
      'priority': 'Öncelik',
      'high': 'Yüksek',
      'medium': 'Orta',
      'low': 'Düşük',
      'run_saved_search': 'Kayıtlı Aramayı Çalıştır',
      'delete_saved_search': 'Kayıtlı Aramayı Sil',
      
      // Mood Tracking
      'mood_tracking': 'Mood Tracking',
      'mood_entry': 'Mood Girişi',
      'mood_goals': 'Mood Hedefleri',
      'mood_analytics': 'Mood Analizi',
      'mood_score': 'Mood Skoru',
      'anxiety_level': 'Anksiyete Seviyesi',
      'energy_level': 'Enerji Seviyesi',
      'sleep_quality': 'Uyku Kalitesi',
      'very_bad': 'Çok Kötü',
      'bad': 'Kötü',
      'neutral': 'Nötr',
      'good': 'İyi',
      'very_good': 'Çok İyi',
      'mood_notes': 'Mood Notları',
      'mood_tags': 'Mood Etiketleri',
      'add_mood_entry': 'Mood Girişi Ekle',
      'edit_mood_entry': 'Mood Girişi Düzenle',
      'view_mood_details': 'Mood Detayları',
      'mood_trend': 'Mood Trendi',
      'weekly_summary': 'Haftalık Özet',
      'best_day': 'En İyi Gün',
      'worst_day': 'En Kötü Gün',
      'average_sleep': 'Ortalama Uyku',
      'active_goals': 'Aktif Hedefler',
      'goal_progress': 'Hedef İlerlemesi',
      'target_value': 'Hedef Değer',
      'current_value': 'Mevcut Değer',
      'goal_status': 'Hedef Durumu',
      'in_progress': 'Devam Ediyor',
      'completed': 'Tamamlandı',
      'update_goal_progress': 'Hedef İlerlemesini Güncelle',
      
      // AI Asistan
      'ai_assistant': 'AI Asistan',
      'chat_with_ai': 'AI ile Sohbet Et',
      'type_message': 'Mesajınızı yazın...',
      'send_message': 'Mesaj Gönder',
      'clear_chat': 'Sohbeti Temizle',
      'ai_help': 'AI Yardım',
      'ai_can_help': 'AI Asistan size şu konularda yardımcı olabilir:',
      'patient_management_help': 'Hasta yönetimi ve takibi',
      'appointment_help': 'Randevu planlama ve yönetimi',
      'prescription_help': 'E-reçete sistemi',
      'billing_help': 'Faturalandırma',
      'insurance_help': 'Sigorta entegrasyonu',
      'mood_help': 'Mood tracking',
      'voice_notes_help': 'Sesli notlar',
      'telemedicine_help': 'Telemedicine',
      'security_help': 'Güvenlik ayarları',
      'analytics_help': 'Analitik ve raporlama',
      'ask_questions': 'Sorularınızı doğal dilde sorabilirsiniz.',
      
      // Dil Ayarları
      'language_settings': 'Dil Ayarları',
      'select_language': 'Dil Seçin',
      'turkish': 'Türkçe',
      'english': 'English',
      'german': 'Deutsch',
      'french': 'Français',
      'spanish': 'Español',
      'arabic': 'العربية',
      'language_changed': 'Dil değiştirildi',
      'restart_required': 'Değişikliklerin etkili olması için uygulamayı yeniden başlatın',
    },
    'en': {
      // General
      'app_title': 'PsyClinic AI',
      'welcome': 'Welcome',
      'login': 'Login',
      'logout': 'Logout',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'filter': 'Filter',
      'close': 'Close',
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Info',
      
      // Dashboard
      'dashboard': 'Dashboard',
      'home': 'Home',
      'patients': 'Patients',
      'appointments': 'Appointments',
      'ai_diagnosis': 'AI Diagnosis',
      'telemedicine': 'Telemedicine',
      'security': 'Security',
      'analytics': 'Analytics',
      'roles': 'Roles',
      'patient_portal': 'Patient Portal',
      'voice_notes': 'Voice Notes',
      'billing': 'Billing',
      'insurance': 'Insurance',
      'e_prescription': 'E-Prescription',
      'advanced_search': 'Search',
      'mood_tracking': 'Mood',
      'ai_assistant': 'AI Assistant',
      
      // Patient Management
      'patient_management': 'Patient Management',
      'patient_name': 'Patient Name',
      'patient_id': 'Patient ID',
      'diagnosis': 'Diagnosis',
      'last_session': 'Last Session',
      'status': 'Status',
      'active': 'Active',
      'inactive': 'Inactive',
      'new_patient': 'New Patient',
      'patient_details': 'Patient Details',
      'patient_history': 'Patient History',
      'add_patient': 'Add Patient',
      'edit_patient': 'Edit Patient',
      'delete_patient': 'Delete Patient',
      
      // Appointment System
      'appointment_system': 'Appointment System',
      'appointment_date': 'Appointment Date',
      'appointment_time': 'Appointment Time',
      'doctor': 'Doctor',
      'appointment_type': 'Appointment Type',
      'appointment_status': 'Appointment Status',
      'scheduled': 'Scheduled',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'rescheduled': 'Rescheduled',
      'new_appointment': 'New Appointment',
      'reschedule_appointment': 'Reschedule Appointment',
      'cancel_appointment': 'Cancel Appointment',
      
      // AI Diagnosis
      'ai_diagnosis': 'AI-Powered Diagnosis',
      'symptoms': 'Symptoms',
      'patient_history_input': 'Patient History',
      'get_diagnosis': 'Get Diagnosis',
      'ai_result': 'AI Diagnosis Result',
      'risk_assessment': 'Risk Assessment',
      'recommended_treatment': 'Recommended Treatment',
      'possible_diagnosis': 'Possible Diagnosis',
      
      // Telemedicine
      'video_call': 'Video Call',
      'start_call': 'Start Call',
      'end_call': 'End Call',
      'mute_mic': 'Mute Microphone',
      'unmute_mic': 'Unmute Microphone',
      'turn_off_camera': 'Turn Off Camera',
      'turn_on_camera': 'Turn On Camera',
      'screen_share': 'Screen Share',
      'local_video': 'Local Video Stream',
      'remote_video': 'Remote Video Stream',
      
      // Security
      'security_settings': 'Security Settings',
      'biometric_auth': 'Biometric Authentication',
      'two_factor_auth': 'Two-Factor Authentication',
      'audit_logs': 'Audit Logs',
      'encryption_settings': 'Encryption Settings',
      'password_change': 'Change Password',
      'security_report': 'Security Report',
      
      // Analytics
      'analytics_reporting': 'Analytics and Reporting',
      'total_patients': 'Total Patients',
      'monthly_revenue': 'Monthly Revenue',
      'average_sessions': 'Average Sessions',
      'new_patients_this_month': 'New Patients (This Month)',
      'monthly_sessions': 'Monthly Sessions',
      'performance_metrics': 'Performance Metrics',
      'trend_analysis': 'Trend Analysis',
      
      // Patient Portal
      'patient_portal': 'Patient Portal',
      'book_appointment': 'Book Appointment',
      'send_message': 'Send Message',
      'make_payment': 'Make Payment',
      'upload_file': 'Upload File',
      'upcoming_appointments': 'Upcoming Appointments',
      'recent_messages': 'Recent Messages',
      'treatment_plan': 'Treatment Plan',
      'lab_results': 'Lab Results',
      'download': 'Download',
      'share': 'Share',
      
      // Voice Notes
      'voice_notes': 'Voice Notes',
      'start_recording': 'Start Recording',
      'pause_recording': 'Pause Recording',
      'stop_recording': 'Stop Recording',
      'play_note': 'Play Note',
      'pause_note': 'Pause Note',
      'recording_duration': 'Recording Duration',
      'transcription': 'Transcription',
      'note_title': 'Note Title',
      'save_note': 'Save Note',
      'delete_note': 'Delete Note',
      'no_voice_notes': 'No voice notes yet',
      
      // Billing
      'billing_system': 'Billing System',
      'invoices': 'Invoices',
      'payments': 'Payments',
      'insurance_claims': 'Insurance Claims',
      'total_invoice': 'Total Invoice',
      'pending': 'Pending',
      'overdue': 'Overdue',
      'paid': 'Paid',
      'invoice_id': 'Invoice ID',
      'due_date': 'Due Date',
      'total_amount': 'Total Amount',
      'payment_method': 'Payment Method',
      'bank_transfer': 'Bank Transfer',
      'credit_card': 'Credit Card',
      'cash': 'Cash',
      'create_invoice': 'Create Invoice',
      'send_invoice': 'Send Invoice',
      'view_invoice': 'View Invoice',
      
      // Insurance
      'insurance_integration': 'Insurance Integration',
      'insurance_companies': 'Insurance Companies',
      'patient_insurance': 'Patient Insurance',
      'claims': 'Claims',
      'active_companies': 'Active Companies',
      'average_coverage': 'Average Coverage',
      'policy_number': 'Policy Number',
      'coverage_type': 'Coverage Type',
      'coverage_amount': 'Coverage Amount',
      'remaining_amount': 'Remaining Amount',
      'valid_from': 'Valid From',
      'valid_to': 'Valid To',
      'expired': 'Expired',
      'exhausted': 'Exhausted',
      'sync_company': 'Sync Company',
      'view_company_details': 'View Company Details',
      'check_coverage': 'Check Coverage',
      'view_insurance_details': 'View Insurance Details',
      'claim_amount': 'Claim Amount',
      'approved_amount': 'Approved Amount',
      'claim_status': 'Claim Status',
      'approved': 'Approved',
      'under_review': 'Under Review',
      'rejected': 'Rejected',
      'track_claim': 'Track Claim',
      
      // E-Prescription
      'e_prescription_system': 'E-Prescription System',
      'medications': 'Medications',
      'prescriptions': 'Prescriptions',
      'pharmacies': 'Pharmacies',
      'medication_name': 'Medication Name',
      'generic_name': 'Generic Name',
      'dosage': 'Dosage',
      'form': 'Form',
      'category': 'Category',
      'stock': 'Stock',
      'price': 'Price',
      'prescription_required': 'Prescription Required',
      'side_effects': 'Side Effects',
      'interactions': 'Interactions',
      'add_to_prescription': 'Add to Prescription',
      'prescription_id': 'Prescription ID',
      'frequency': 'Frequency',
      'duration': 'Duration',
      'instructions': 'Instructions',
      'insurance_coverage': 'Insurance Coverage',
      'patient_payment': 'Patient Payment',
      'send_to_pharmacy': 'Send to Pharmacy',
      'pharmacy_name': 'Pharmacy Name',
      'pharmacy_address': 'Pharmacy Address',
      'pharmacy_phone': 'Pharmacy Phone',
      'distance': 'Distance',
      'rating': 'Rating',
      'delivery_available': 'Delivery Available',
      'call_pharmacy': 'Call Pharmacy',
      'send_prescription': 'Send Prescription',
      
      // Advanced Search
      'advanced_search': 'Advanced Search',
      'search_query': 'Search Query',
      'search_category': 'Search Category',
      'date_range': 'Date Range',
      'all_categories': 'All Categories',
      'last_7_days': 'Last 7 Days',
      'last_30_days': 'Last 30 Days',
      'last_3_months': 'Last 3 Months',
      'last_6_months': 'Last 6 Months',
      'last_year': 'Last Year',
      'all_time': 'All Time',
      'saved_searches': 'Saved Searches',
      'trends': 'Trends',
      'search_results': 'Search Results',
      'no_results': 'No results found',
      'search_history': 'Search History',
      'advanced_filters': 'Advanced Filters',
      'priority': 'Priority',
      'high': 'High',
      'medium': 'Medium',
      'low': 'Low',
      'run_saved_search': 'Run Saved Search',
      'delete_saved_search': 'Delete Saved Search',
      
      // Mood Tracking
      'mood_tracking': 'Mood Tracking',
      'mood_entry': 'Mood Entry',
      'mood_goals': 'Mood Goals',
      'mood_analytics': 'Mood Analytics',
      'mood_score': 'Mood Score',
      'anxiety_level': 'Anxiety Level',
      'energy_level': 'Energy Level',
      'sleep_quality': 'Sleep Quality',
      'very_bad': 'Very Bad',
      'bad': 'Bad',
      'neutral': 'Neutral',
      'good': 'Good',
      'very_good': 'Very Good',
      'mood_notes': 'Mood Notes',
      'mood_tags': 'Mood Tags',
      'add_mood_entry': 'Add Mood Entry',
      'edit_mood_entry': 'Edit Mood Entry',
      'view_mood_details': 'View Mood Details',
      'mood_trend': 'Mood Trend',
      'weekly_summary': 'Weekly Summary',
      'best_day': 'Best Day',
      'worst_day': 'Worst Day',
      'average_sleep': 'Average Sleep',
      'active_goals': 'Active Goals',
      'goal_progress': 'Goal Progress',
      'target_value': 'Target Value',
      'current_value': 'Current Value',
      'goal_status': 'Goal Status',
      'in_progress': 'In Progress',
      'completed': 'Completed',
      'update_goal_progress': 'Update Goal Progress',
      
      // AI Assistant
      'ai_assistant': 'AI Assistant',
      'chat_with_ai': 'Chat with AI',
      'type_message': 'Type your message...',
      'send_message': 'Send Message',
      'clear_chat': 'Clear Chat',
      'ai_help': 'AI Help',
      'ai_can_help': 'AI Assistant can help you with:',
      'patient_management_help': 'Patient management and tracking',
      'appointment_help': 'Appointment planning and management',
      'prescription_help': 'E-prescription system',
      'billing_help': 'Billing',
      'insurance_help': 'Insurance integration',
      'mood_help': 'Mood tracking',
      'voice_notes_help': 'Voice notes',
      'telemedicine_help': 'Telemedicine',
      'security_help': 'Security settings',
      'analytics_help': 'Analytics and reporting',
      'ask_questions': 'You can ask questions in natural language.',
      
      // Language Settings
      'language_settings': 'Language Settings',
      'select_language': 'Select Language',
      'turkish': 'Türkçe',
      'english': 'English',
      'german': 'Deutsch',
      'french': 'Français',
      'spanish': 'Español',
      'arabic': 'العربية',
      'language_changed': 'Language changed',
      'restart_required': 'Please restart the app for changes to take effect',
    },
  };

  Locale get currentLocale => _currentLocale;
  bool get isInitialized => _isInitialized;

  Future<void> initialize() async {
    if (_isInitialized) return;
    
    final prefs = await SharedPreferences.getInstance();
    final languageCode = prefs.getString('language_code') ?? 'tr';
    final countryCode = prefs.getString('country_code') ?? 'TR';
    
    _currentLocale = Locale(languageCode, countryCode);
    _isInitialized = true;
    notifyListeners();
  }

  Future<void> changeLanguage(Locale locale) async {
    if (_currentLocale == locale) return;
    
    _currentLocale = locale;
    notifyListeners();
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', locale.languageCode);
    await prefs.setString('country_code', locale.countryCode ?? '');
  }

  String translate(String key) {
    final translations = _translations[_currentLocale.languageCode];
    if (translations == null) {
      // Fallback to Turkish if current language not found
      final fallbackTranslations = _translations['tr'];
      return fallbackTranslations?[key] ?? key;
    }
    return translations[key] ?? key;
  }

  List<Locale> get supportedLocales => [
    const Locale('tr', 'TR'),
    const Locale('en', 'US'),
    const Locale('de', 'DE'),
    const Locale('fr', 'FR'),
    const Locale('es', 'ES'),
    const Locale('ar', 'SA'),
  ];

  Map<String, String> get supportedLanguages => {
    'tr': translate('turkish'),
    'en': translate('english'),
    'de': translate('german'),
    'fr': translate('french'),
    'es': translate('spanish'),
    'ar': translate('arabic'),
  };
}
