#!/usr/bin/env bash
# PsyClinicAI Hetzner Deploy Script
# Usage: ssh root@46.225.181.130 'bash -s' < deploy-hetzner.sh
# Or:    scp this to server, then `bash deploy-hetzner.sh`

set -euo pipefail

NETWORK="ilhanostranscript_internal"
APP_DIR="/opt/psyclinicai-web"
DIST_DIR="${APP_DIR}/dist"
CONTAINER_NAME="psyclinicai-web"
NGINX_CONF_DIR="/opt/ilhanostranscript/nginx/conf.d"
NGINX_CONTAINER="ilhanostranscript-nginx"
DOMAIN="psyclinicai.com"

echo "=== Step 1: Sanity checks ==="
[ -d "$DIST_DIR" ] || { echo "ERROR: $DIST_DIR yok, once rsync yap"; exit 1; }
docker network inspect "$NETWORK" >/dev/null || { echo "ERROR: network $NETWORK yok"; exit 1; }
[ -d "$NGINX_CONF_DIR" ] || { echo "ERROR: nginx conf.d yok"; exit 1; }
echo "  OK - $(ls $DIST_DIR | wc -l) dosya dist'te, network var, conf.d var"

echo "=== Step 2: Stop & remove eski container (varsa) ==="
docker rm -f "$CONTAINER_NAME" 2>/dev/null || true

echo "=== Step 3: Yeni psyclinicai-web container calistir ==="
docker run -d \
  --name "$CONTAINER_NAME" \
  --network "$NETWORK" \
  --restart unless-stopped \
  -v "${DIST_DIR}:/usr/share/nginx/html:ro" \
  nginx:alpine
sleep 2
docker ps --filter "name=$CONTAINER_NAME" --format "  {{.Names}} | {{.Status}} | {{.Ports}}"

echo "=== Step 4: Nginx reverse proxy config olustur ==="
cat > "${NGINX_CONF_DIR}/psyclinicai.conf" <<NGINX_CONF
# PsyClinicAI - Generated by deploy-hetzner.sh
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # HTTP serve (SSL henuz alinmadi)
    location / {
        proxy_pass http://${CONTAINER_NAME}:80;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX_CONF
echo "  OK - ${NGINX_CONF_DIR}/psyclinicai.conf yazildi"

echo "=== Step 5: Nginx test + reload ==="
docker exec "$NGINX_CONTAINER" nginx -t
docker exec "$NGINX_CONTAINER" nginx -s reload
echo "  OK - nginx reloaded"

echo "=== Step 6: HTTP test ==="
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Host: ${DOMAIN}" http://localhost/ || echo "fail")
echo "  Local Host:${DOMAIN} test: HTTP $HTTP_CODE"

echo ""
echo "=== DEPLOY BASARILI ==="
echo "  Container: $CONTAINER_NAME running"
echo "  Nginx config: ${NGINX_CONF_DIR}/psyclinicai.conf"
echo "  Domain: $DOMAIN (DNS A record -> 46.225.181.130 olmali)"
echo ""
echo "=== Sonraki adimlar (SSL icin) ==="
echo "  1) DNS kontrolu: dig +short ${DOMAIN}"
echo "  2) Let's Encrypt SSL al:"
echo "     docker run --rm \\"
echo "       -v ilhanostranscript_certbot-etc:/etc/letsencrypt \\"
echo "       -v ilhanostranscript_certbot-webroot:/var/www/certbot \\"
echo "       certbot/certbot certonly --webroot -w /var/www/certbot \\"
echo "       -d ${DOMAIN} -d www.${DOMAIN} \\"
echo "       --email caglarilhann@gmail.com --agree-tos --non-interactive"
echo "  3) SSL alindiktan sonra psyclinicai.conf'a 443 block ekle"
echo "  4) docker exec ${NGINX_CONTAINER} nginx -s reload"
