// Placeholder generated by hand. Replace by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=<your-firebase-project-id>
//
// The bootstrap layer (`lib/services/data/firebase_bootstrap.dart`) catches
// the resulting initialization error when these placeholders are still in
// place, so the app continues to run in "offline / no-backend" mode for
// landing-page and demo flows.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.macOS:
        return _macos;
      default:
        return _web;
    }
  }

  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'TODO-flutterfire-configure',
    appId: 'TODO-flutterfire-configure',
    messagingSenderId: 'TODO-flutterfire-configure',
    projectId: 'TODO-flutterfire-configure',
    authDomain: 'TODO-flutterfire-configure.firebaseapp.com',
    storageBucket: 'TODO-flutterfire-configure.appspot.com',
  );

  static const FirebaseOptions _ios = _web;
  static const FirebaseOptions _android = _web;
  static const FirebaseOptions _macos = _web;
}
