/// N14 — Supply chain SBOM + license policy (pinned helper).
///
/// **Why this exists**: SOC 2 CC9.2 + NIST SP 800-161 supply-chain
/// + EU CRA (Cyber Resilience Act, in force from 2027) all require
/// the controller to (a) maintain an SBOM, (b) act on CVEs within
/// a documented window, and (c) only ship dependencies under
/// allowed licenses. Today none of those are pinned in code; a
/// `pubspec.yaml` change can quietly add a GPL-licensed package
/// or a vendor whose CVE we never noticed. This catalog pins:
///   1. Allowed dependency licenses (permissive only on the prod
///      bundle; the test-only allow-list is wider).
///   2. CVE severity → response SLA + escalation channel.
///   3. SBOM regeneration cadence + storage path.
///
/// **Out of scope** (separate PRs):
///   * Cloud Function that diffs `pubspec.yaml` against the
///     allowed-license set in CI.
///   * SBOM CycloneDX generator workflow.
///   * CVE auto-triage Cloud Function that joins osv.dev with
///     this catalog's SLA matrix.
library;

/// SPDX license category. Sourced from the SPDX list + curated for
/// our compliance posture.
enum LicenseCategory {
  /// Permissive: MIT, BSD-2/3, Apache-2.0, ISC. Allowed in prod.
  permissive,

  /// Weak copyleft: LGPL-2.1/3.0, MPL-2.0. Allowed in prod with
  /// the caveat that linking semantics + redistribution rules are
  /// honoured; legal review per add.
  weakCopyleft,

  /// Strong copyleft: GPL-2.0, GPL-3.0, AGPL. NOT allowed in our
  /// SaaS bundle (AGPL especially is incompatible with our hosted
  /// model unless the entire app is open-sourced).
  strongCopyleft,

  /// Proprietary: vendor-specific commercial license. Allowed
  /// only when we have a signed paid license + procurement sign-
  /// off (Stripe SDK, Sentry SDK, etc.).
  proprietary,
}

/// Severity of a CVE in a pinned dependency.
enum CveSeverity {
  /// CVSS 9.0+ — RCE, full data exposure, supply-chain pin
  /// compromised.
  critical,

  /// CVSS 7.0–8.9 — privilege escalation, partial data exposure.
  high,

  /// CVSS 4.0–6.9 — DoS, info disclosure of non-PHI metadata.
  medium,

  /// CVSS < 4.0 — best-practice nudges, informational.
  low,
}

/// One pinned license policy row.
class LicensePolicyRecord {
  const LicensePolicyRecord({
    required this.category,
    required this.allowedInProdBundle,
    required this.allowedInTestOnly,
    required this.requiresLegalReview,
    required this.exampleLicenses,
  });

  final LicenseCategory category;

  /// True when the license is OK to ship inside the production
  /// Flutter web / iOS / Android bundle.
  final bool allowedInProdBundle;

  /// True when the license is OK in dev / test dependencies only
  /// (those that never reach a customer device).
  final bool allowedInTestOnly;

  /// True when adding a new package under this category requires
  /// counsel sign-off before merge.
  final bool requiresLegalReview;

  /// Concrete SPDX identifiers in this category.
  final List<String> exampleLicenses;
}

/// One pinned CVE response policy row.
class CveResponsePolicy {
  const CveResponsePolicy({
    required this.severity,
    required this.acknowledgeWithinHours,
    required this.remediationTargetDays,
    required this.escalationOwner,
  });

  final CveSeverity severity;

  /// Max hours from CVE publication to triage acknowledgement.
  final int acknowledgeWithinHours;

  /// Target days to ship an updated dependency (or a documented
  /// mitigation) before the CVE is considered overdue.
  final int remediationTargetDays;

  /// Single accountable role.
  final String escalationOwner;
}

class SupplyChainPolicy {
  const SupplyChainPolicy._();

  /// YYYY-MM stamp — drives the "needs review" badge.
  static const String lastReviewed = '2026-06';

  /// SBOM regenerated by the build pipeline on this cadence.
  /// CycloneDX format; stored under `docs/security/sbom/<YYYY-mm-dd>`.
  static const String sbomFormat = 'CycloneDX 1.5';
  static const int sbomRegenerationDays = 7;
  static const String sbomStoragePathTemplate =
      'docs/security/sbom/<YYYY-mm-dd>/psyclinicai.cyclonedx.json';

  /// Pinned per-category license policy.
  static const List<LicensePolicyRecord> licenses = [
    LicensePolicyRecord(
      category: LicenseCategory.permissive,
      allowedInProdBundle: true,
      allowedInTestOnly: true,
      requiresLegalReview: false,
      exampleLicenses: [
        'MIT',
        'BSD-2-Clause',
        'BSD-3-Clause',
        'Apache-2.0',
        'ISC',
      ],
    ),
    LicensePolicyRecord(
      category: LicenseCategory.weakCopyleft,
      allowedInProdBundle: true,
      allowedInTestOnly: true,
      requiresLegalReview: true,
      exampleLicenses: ['LGPL-2.1', 'LGPL-3.0', 'MPL-2.0'],
    ),
    LicensePolicyRecord(
      category: LicenseCategory.strongCopyleft,
      allowedInProdBundle: false,
      allowedInTestOnly: false,
      requiresLegalReview: true,
      exampleLicenses: ['GPL-2.0', 'GPL-3.0', 'AGPL-3.0'],
    ),
    LicensePolicyRecord(
      category: LicenseCategory.proprietary,
      allowedInProdBundle: true,
      allowedInTestOnly: true,
      requiresLegalReview: true,
      exampleLicenses: [
        'Stripe Commercial',
        'Sentry Commercial',
        'Anthropic Commercial Terms',
      ],
    ),
  ];

  /// Pinned per-severity CVE response policy.
  static const List<CveResponsePolicy> cveResponses = [
    CveResponsePolicy(
      severity: CveSeverity.critical,
      acknowledgeWithinHours: 4,
      remediationTargetDays: 7,
      escalationOwner: 'ciso',
    ),
    CveResponsePolicy(
      severity: CveSeverity.high,
      acknowledgeWithinHours: 24,
      remediationTargetDays: 30,
      escalationOwner: 'cto',
    ),
    CveResponsePolicy(
      severity: CveSeverity.medium,
      acknowledgeWithinHours: 72,
      remediationTargetDays: 90,
      escalationOwner: 'on_call',
    ),
    CveResponsePolicy(
      severity: CveSeverity.low,
      acknowledgeWithinHours: 168,
      remediationTargetDays: 180,
      escalationOwner: 'on_call',
    ),
  ];

  /// Citations the policy is grounded in.
  static const List<String> regulatoryRefs = [
    'SOC 2 CC9.2 vendor + supply chain',
    'NIST SP 800-161 supply-chain risk management',
    'EU CRA (Cyber Resilience Act) — in force from 2027',
    'NIST SP 800-53 SI-2 flaw remediation',
    'OWASP Dependency-Check best practice',
  ];

  static LicensePolicyRecord forLicenseCategory(LicenseCategory c) {
    for (final p in licenses) {
      if (p.category == c) return p;
    }
    throw StateError('No license policy for ${c.name}');
  }

  static CveResponsePolicy forCveSeverity(CveSeverity s) {
    for (final p in cveResponses) {
      if (p.severity == s) return p;
    }
    throw StateError('No CVE response for ${s.name}');
  }
}

/// True when [license] (case-insensitive SPDX id) is OK to ship
/// inside the production bundle.
bool isLicenseAllowedInProd(String license) {
  final lower = license.toLowerCase();
  for (final p in SupplyChainPolicy.licenses) {
    if (!p.allowedInProdBundle) continue;
    for (final l in p.exampleLicenses) {
      if (l.toLowerCase() == lower) return true;
    }
  }
  return false;
}

/// True when [license] is on the explicit deny-list for prod (e.g.
/// GPL family). False when unknown — unknown means "needs legal
/// triage" rather than auto-deny.
bool isLicenseDeniedInProd(String license) {
  final lower = license.toLowerCase();
  for (final p in SupplyChainPolicy.licenses) {
    if (p.allowedInProdBundle) continue;
    for (final l in p.exampleLicenses) {
      if (l.toLowerCase() == lower) return true;
    }
  }
  return false;
}
